FROM golang:1.24.1-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod ./
RUN go mod tidy

COPY . /app

RUN go build -o peer ./eachare.go

FROM alpine:latest AS final_image

WORKDIR /app 

COPY --from=builder /app/peer /app/peer

CMD ["tail", "-f", "/dev/null"]
#CMD [ "app/peer" ]
#ENTRYPOINT ["/app/peer"]